BATCH_SIZE: 128
DATASET_PATH: data/
DATASET_NAME: ZINC
MAX_EPOCHS: 500
SEED: 1
HIDDEN_DIM: 64
PATIENCE: 2
NUM_LAYERS: 4
PROJECT_NAME: Diffeomorphic Graph Neural Networks
ACCELERATOR: gpu
DEVICES: 1
DROPOUT: 0.5
LINEAR_LR: 1.e-4
CONV_LR: 0.001 #0.005 #0.001 #21808071745552915 #1.e-3
LINEAR_WD: 0.00005 #5.e-4
CONV_WD:  0.00001  #0.00001 #0 #0.0001 #042052656050965 #0 #1.e-4
ALPHA_GCN2: 0.0
THETA_GCN2: 0.0
THETA_LR: 0.0001 #0.001
THETA_WD: 0.0
ACTIVATION: cpab_gnn
SHARED_ACTIVATION: True
BACKBONE: gine
TAGS:
  - difw_cpab_base_requires_grad_is_True
TASK: sweep
SEEDS:
  - 1
  - 2
  - 3
  - 4
  - 5
GRAPH_POOLING: mean
TIME_INTEGRATION: 0
THETA_POOLING: sum
THETA_NUM_LAYERS: 2
THETA_HIDDEN_DIM: 64
TRANSFORM_THETA: True
USE_TANH: True
SCHEDULER_STEP_SIZE: 100
RADIUS: 10
REG_COEFF: 0.001
USE_REGULARIZATION: True
TESS_SIZE: 8
TRACK_RUNNING_STATS: True
EPS: 0
CHECKPOINT_PATH: saved_models/GNN
MODEL_NAME: "digraf"


defaults:
  - _self_
  - wandb_sweep: digraf_nodecls_cora
